services:
  horizon-backend:
    build: ./backend
    container_name: horizon-backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - horizon-network

  horizon-frontend:
    build: ./frontend
    container_name: horizon-frontend
    restart: unless-stopped
    depends_on:
      - horizon-backend
    networks:
      - horizon-network
      - adam

  mongodb:
    image: mongo:latest
    container_name: horizon-db
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - horizon-network

networks:
  horizon-network:
    driver: bridge
  adam:
    external: true

volumes:
  mongodb_data:
